### ISSUE TITLE
Not working for user accounts other than ID "0"

### ISSUE THREAD

**Issue by wr-dev** [Offroadcode/Umbraco-2FA#4] opened 2017-05-18 05:38 UTC
Package works great for the main Admin account. However, when trying to use this for other user accounts, I log in, and get presented with the "Specify your two-factor authentication option" screen, as expected. 

However, when I then click on GoogleAuthenticator, I get a 500 error in console with the error below.

In my FortressUser2FASettings table, I only have an entry for User ID 0.

I'm going to try and work this out, but if you have any ideas?

Thanks!

{Message: "An error has occurred.",…}
ExceptionMessage
:
"This account has already setup GoogleAuthenticator"
ExceptionType
:
"System.UnauthorizedAccessException"
Message
:
"An error has occurred."
StackTrace
:
"   at Orc.Fortress.Controllers.TwoFactorSetupController.SetupGoogleAuth()
↵   at lambda_method(Closure , Object , Object[] )
↵   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
↵   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
↵   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
↵--- End of stack trace from previous location where exception was thrown ---
↵   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
↵   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
↵   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
↵--- End of stack trace from previous location where exception was thrown ---
↵   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
↵   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
↵   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
↵--- End of stack trace from previous location where exception was thrown ---
↵   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
↵   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
↵   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"

**Comment by wr-dev** [comment] 2017-05-18 06:14
The problem seems to be in ``Controllers.TwoFactorSetupController.SetupGoogleAuth()`` - this line

``var user =  SignInManager.GetVerifiedUserId();``

... always returns 0.

**Comment by PeteDuncanson** [comment] 2017-05-18 09:43
Thanks for reporting this one, wonder if its an issue with when we poke the userID into the table or when we pull it out via GetVerifiedUserId(). I suspect it will be at the point of saving to the table (probably using the admin id to create the entry rather than the one for the currently edited user from the front end at a guess. Will take a look.

**Comment by wr-dev** [comment] 2017-05-18 10:22
Hi Pete

Thanks for coming back. I've tried to find a workaround, but wasn't able to come up with one. It seems that, when you show the selection form, and the subsequent POST to SetUpGoogleAuth(), when it tries to GetVerifiedUserId(), that always returns 0. I've tried to get the current User ID server side, without success. However, after the call to PostLogin, the correct UserID is returned (with the view name) so perhaps it could be passed in to the SetUpGoogleAuth action?

Cheers,

Tom.

**Comment by wr-dev** [comment] 2017-05-23 09:26
Hello!

I was wondering whether you'd had chance to find a fix/update for this, or if I can do anything to help?

Thank you!

Tom.

**Comment by PeteDuncanson** [comment] 2017-05-23 13:06
Hi Tom,

Kyle has been take a look and I've got Ste assigned to it later this week. We are hoping to get it into a PR for Core so this package might not be needed anymore but that would require us awaiting a 7.7 release so we suspect we will get this package running too as a stop gap.

Watch this space.

Pete

**Comment by Frosty2** [comment] 2017-05-31 09:28
I've experienced the same issue. If i hard code the id to replace GetVerifiedUserId  i still get tripped up on backoffice endpoint "PostVerify2FACode" which is returning "User is locked out". I suppose as it's not authenticated it can't reach this endpoint. Also, I can't locate this endpoint in the source.

**Comment by wr-dev** [comment] 2017-06-01 09:39
Hi Pete, Kyle, Ste.

Any update on this issue? We've got a number of clients who are asking for 2FA, now that the EU GDPR legislation is close on the horizon. You've created such an elegant solution I'd rather not start from scratch... 

If we can do anything to help, with either finding a work around of convincing UHQ to bake it in to 7.7, please let me know.

Thank you, Tom.

**Comment by PeteDuncanson** [comment] 2017-06-02 11:52
Hi @wr-dev and @Frosty2,

We are working on it this week/next. Hoping to have it sorted before Code Garden so you know (even if its just a PR into Core with the fix) but we will have something at least, ideally have it fixed but until we find the cause we can't promise it.

Also working on getting it into Core too :)

Cheers

Pete

**Comment by wr-dev** [comment] 2017-06-21 08:21
Any updates @PeteDuncanson? Here to help if we can.

**Comment by tlfzhylj** [comment] 2017-06-27 20:21
Any news on this one, @cssquirrel, @PeteDuncanson?

Thanks.

**Comment by PeteDuncanson** [comment] 2017-06-28 10:38
Hi guys,

We stopped work on this just before Code Garden as it was tweeted out that HQ had got this working in Core, why would we fix this if its in Core right? Turns out they haven't really, they have a chunk of code you can drop in and then set it up yourself which is not quite the same as a nice tidy package that does it all for you and supports you while you set it up. As a result we are warming this one back up so this package can have some legs until Core get it in there properly once and for all. Its been a busy few weeks since getting back from Code Garden but I've got some time scheduled in for fixing this one next week.

Cheers

Pete

**Comment by tlfzhylj** [comment] 2017-07-10 13:30
Did you get the time to look into it last week, @PeteDuncanson?
Appreciate your work.

**Comment by PeteDuncanson** [comment] 2017-07-10 14:27
Yes we did, hit a snag and are awaiting confirmation on if its a "fixable" thing or not.

**Comment by Gholie** [comment] 2017-08-04 07:09
Did you make any progress as to whether it is fixable?

Thanks for your work!

**Comment by PeteDuncanson** [comment] 2017-08-04 09:42
Holidays and babies stopped play on this one. All back on board now and playing catch up so will warm this one back up. Thanks for the prod (keep them coming)

**Comment by ed-parry** [comment] 2017-08-31 16:23
Any news one this one? In a similar situation of looking for 2FA, but only working for the admin user is a showstopper for us :(

**Comment by PeteDuncanson** [comment] 2017-09-08 10:23
Just a heads up for those following this one. We've rewritten the way the login works to get around the issue that was stopping us and this seems to have worked. Doing some final testing and then we hope to get this out to you. Sorry for the hold up but thanks for the interest. Working hard on trying to get it out the door so you can get it installed :)

**Comment by wr-dev** [comment] 2017-09-08 10:28
Great news Pete, thanks for the update and the hard word. Still actively following, looking forward to testing and deploying!

**Comment by ahsanjaffri** [comment] 2017-10-05 10:35
@PeteDuncanson when we can expect this fix available? I am still facing the same issue.

**Comment by tlfzhylj** [comment] 2017-11-01 14:12
@PeteDuncanson Any news?

**Comment by steroberts89** [comment] 2017-11-01 14:17
Hi All,

Just to update you we have found the cause of the issue living somewhere in the integration with Umbraco and ASP.Net Owin identity where something is failing.

We have opened an support issue with umbraco to try to find the root cause of this http://issues.umbraco.org/issue/U4-10620


Thanks
Stephen

**Comment by HarveyWilliams** [comment] 2017-11-06 16:46
Thanks for the work on this very promising package.

I've just tested on 7.6.11 and I am getting the same issue.

Does `SignInManager.GetVerifiedUserId()` only work if the useris logged in? That would explain why it's possible to generate but not verify.

Thanks again.

**Comment by PeteDuncanson** [comment] 2017-11-14 17:03
Thanks for the test Harvey, will take another look asap.

**Closed** 2018-02-23 16:35 UTC
